#' Extract TAC data from kinfitresults
#'
#' Extract TAC data from a kinfitresults.mat file
#'
#' @param matfile Filename of the kinfitresults file
#'
#' @return List with the sizes of all rois, the subject name, PET number, and
#'   TAC data
#' @export
#'
#' @examples
#' abcd_out <- kfresults_getData('abcd_1_kinfitresults.mat')
#'
kfresults_getData <- function(matfile) {

  # Checks

  matfile <- basename(matfile)

  n_underscores <- stringr::str_count(basename(matfile), "_")

  if (n_underscores == 2) {
    details <- stringr::str_split_fixed(basename(matfile), pattern = "_", n = 3)
    Subjname <- details[, 1]
    PETNo <- as.numeric(details[, 2])
  }

  if (n_underscores == 3) {
    details <- stringr::str_split_fixed(basename(matfile), pattern = "_", n = 4)
    Subjname <- paste(details[, 1], details[, 2], sep = "_")
    PETNo <- as.numeric(details[, 3])
  }

  if (n_underscores != 2 & n_underscores != 3) {
    stop("\nThere should be either two or three underscores in the filename.
         Either this file is incorrectly named with its pipeline output,
         or it is not a kinfitresults file.")
  }


  # Doing the deeds

  kfresults <- R.matlab::readMat(matfile)

  times <- as.numeric(kfresults$data[, , 1]$troi) / 60
  durations <- c(0, as.numeric(kfresults$data[, , 1]$stats[, , 1]$times[, , 1]$duration) / 60)

  gm_tacdata <- as.data.frame(kfresults$data[, , 1]$stats[, , 1]$greymasked[, , 1]$mean)
  raw_tacdata <- as.data.frame(kfresults$data[, , 1]$stats[, , 1]$raw[, , 1]$mean)

  tacdata <- raw_tacdata

  roinames <- unlist(kfresults$data[, , 1]$stats[, , 1]$roinames)
  roinames <- gsub("#", "gm", roinames)

  gmrois <- which(grepl(pattern = "gm", roinames))

  tacdata[, gmrois] <- gm_tacdata[, gmrois]

  names(tacdata) <- roinames

  tacdata <- rbind(0, tacdata)

  tacdata$times <- times
  tacdata$durations <- durations
  tacdata$weights <- unlist(kfresults$data[, , 1]$weights[, 1])

  gm_roisizes <- kfresults$data[, , 1]$stats[, , 1]$greymasked[, , 1]$vol[1, ]
  raw_roisizes <- kfresults$data[, , 1]$stats[, , 1]$raw[, , 1]$vol[1, ]

  roisizes <- raw_roisizes
  roisizes[gmrois] <- gm_roisizes[gmrois]
  roisizes <- data.frame(ROI = roinames, Volume = roisizes)


  out <- list(roisizes = roisizes, tacdata = tacdata, Subjname = Subjname, PETNo = PETNo)

  return(out)
}




#' Extract TAC data from roistats
#'
#' Extract TAC data from a kinfitresults.mat file
#'
#' @param matfile Filename of the roistats file
#'
#' @return List with the sizes of all rois, the subject name, PET number, and
#'   TAC data
#' @export
#'
#' @examples
#' abcd_out <- roistats_getData('abcd_dynpet1_roistats.mat')
#'
roistats_getData <- function(matfile) {

  # Checks

  matfile <- basename(matfile)

  n_underscores <- stringr::str_count(basename(matfile), "_")

  if (n_underscores == 2) {
    details <- stringr::str_split_fixed(basename(matfile), pattern = "_", n = 2)
    Subjname <- details[, 1]
    PETNo <- as.numeric(stringr::str_match(matfile, ".*dynpet(\\d+).*")[2])
  }

  if (n_underscores == 3) {
    details <- stringr::str_split_fixed(basename(matfile), pattern = "_", n = 3)
    Subjname <- paste(details[, 1], details[, 2], sep = "_")
    PETNo <- as.numeric(stringr::str_match(matfile, ".*dynpet(\\d+).*")[2])
  }

  if (n_underscores != 2 & n_underscores != 3) {
    stop("\nThere should be either two or three underscores in the filename.
         Either this file is incorrectly named with its pipeline output,
         or it is not a roistats file.")
  }


  # Doing the deeds


  roistats <- R.matlab::readMat(matfile)

  times <- as.numeric(roistats$stats[, , 1]$times[, , 1]$center)
  gm_tacdata <- as.data.frame(unlist(roistats$stats[, , 1]$greymasked[3][[1]]))
  raw_tacdata <- as.data.frame(unlist(roistats$stats[, , 1]$raw[3][[1]]))

  roinames <- unlist(roistats$stats[, , 1]$roinames)
  roinames <- gsub("#", "gm", roinames)
  gmrois <- which(grepl(pattern = "gm", roinames))

  tacdata <- raw_tacdata
  tacdata[, gmrois] <- gm_tacdata[, gmrois]
  names(tacdata) <- roinames
  tacdata <- rbind(0, tacdata)

  tacdata <- cbind(c(0, times), tacdata)
  names(tacdata)[1] <- "Times"

  gm_roisizes <- roistats$stats[, , 1]$greymasked[, , 1]$vol[1, ]
  raw_roisizes <- roistats$stats[, , 1]$raw[, , 1]$vol[1, ]

  roisizes <- raw_roisizes
  roisizes[gmrois] <- gm_roisizes[gmrois]

  details <- stringr::str_split_fixed(basename(matfile), pattern = "_", n = 2)
  Subjname <- details[, 1]
  PETNo <- as.numeric(stringr::str_match(matfile, ".*dynpet(\\d+).*")[2])

  out <- list(roisizes = roisizes, tacdata = tacdata, Subjname = Subjname, PETNo = PETNo)

  return(out)
}


#' Creates a BIDS list from a pipeline anc.mat file
#'
#' This function creates a BIDS list from a pipeline anc file.
#'
#' @param ancmat_file The anc.mat file generated by the pipeline.
#'
#' @return A list in BIDS structure
#' @export
#'
#' @examples
ancmat_getData <- function(ancmat_file) {

  # Checks

  ancmat_inlocation <- ancmat_file
  ancmat_file <- basename(ancmat_file)

  n_underscores <- stringr::str_count(basename(ancmat_file), "_")

  if (n_underscores == 2) {
    details <- stringr::str_split_fixed(basename(ancmat_file), pattern = "_", n = 2)
    Subjname <- details[, 1]
    PETNo <- as.numeric(stringr::str_match(ancmat_file, paste0(Subjname, "_(\\d+)_anc.mat"))[2])
  }

  if (n_underscores == 3) {
    details <- stringr::str_split_fixed(basename(ancmat_file), pattern = "_", n = 3)
    Subjname <- paste(details[, 1], details[, 2], sep = "_")
    PETNo <- as.numeric(stringr::str_match(ancmat_file, paste0(Subjname, "_(\\d+)_anc.mat"))[2])
  }

  if (n_underscores != 2 & n_underscores != 3) {
    stop("\nThere should be either two or three underscores in the filename.
         Either this file is incorrectly named with its pipeline output,
         or it is not an ancmat file.")
  }


  # Doing the deeds


  ancmat <- R.matlab::readMat(ancmat_inlocation, drop=TRUE)

  Info <- list(
    Tomograph = ancmat$Info[, , 1]$tomograph[1],
    Anaesthesia = ancmat$Info[, , 1]$anaesthesia[1],
    BodyPart = ancmat$Info[, , 1]$bodyPart[1],
    #Unit = ,
    Tracer = list(
      Name = ancmat$Info[, , 1]$Tracer[, , 1]$name[1],
      Isotope = ancmat$Info[, , 1]$Tracer[, , 1]$isotope[1],
      MW = ancmat$Info[, , 1]$Tracer[, , 1]$MW[1],
      InjectionType = ancmat$Info[, , 1]$Tracer[, , 1]$injectionType[1]
      ),
    Pharmaceutical = list(
      Name = ancmat$Info[, , 1]$Pharmaceutical[,,1]$name[1],
      DoseAmount = ancmat$Info[, , 1]$Pharmaceutical[,,1]$doseAmount[1],
      DoseUnits = ancmat$Info[, , 1]$Pharmaceutical[,,1]$doseUnits[1],
      DoseRegimen = ancmat$Info[, , 1]$Pharmaceutical[,,1]$doseRegimen[1],
      DoseTime = ancmat$Info[, , 1]$Pharmaceutical[,,1]$doseTime[1],
      DoseTimeUnits = ancmat$Info[, , 1]$Pharmaceutical[,,1]$doseTimeUnits[1]
      )
    )

  Radiochem = list(
    InjectedRadioactivity = ancmat$Radiochem[,,1]$injectedRadioactivity[1],
    InjectedRadioactivityUnits = ancmat$Radiochem[,,1]$injectedRadioactivityUnits[1],
    InjectedMass = ancmat$Radiochem[,,1]$injectedMass[1],
    InjectedMassUnits = ancmat$Radiochem[,,1]$injectedMassUnits[1],
    SpecificRadioactivity = ancmat$Radiochem[,,1]$specificRadioactivity[1],
    SpecificRadioactivityUnits = ancmat$Radiochem[,,1]$specificRadioactivityUnits[1],
    #SpecificRadioactivityMeasTime = ancmat$Radiochem[,,1]$specificRadioactivity[1],
    MinPurity = ancmat$Radiochem[,,1]$minPurity[1],
    MinPurityUnits = ancmat$Radiochem[,,1]$minPurityUnits[1]
  )

  Time = list(
    ScanStart = ancmat$Time[,,1]$scanStart[1],
    ScanStartUnits = ancmat$Time[,,1]$scanStartUnits[1],
    InjectionStart = ancmat$Time[,,1]$injectionStart[1],
    InjectionStartUnits = ancmat$Time[,,1]$injectionStartUnits[1],
    InjectionEnd = ancmat$Time[,,1]$injectionEnd[1],
    InjectionEndUnits = ancmat$Time[,,1]$injectionEndUnits[1],
    FrameTime = list(
      Labels = unlist(ancmat$Time[,,1]$FrameTimes[,,1]$labels),
      Units = unlist(ancmat$Time[,,1]$FrameTimes[,,1]$units),
      Values = unlist(ancmat$Time[,,1]$FrameTimes[,,1]$values)
    )
  )

  Plasma = list(
    FreeFraction = ancmat$Plasma[,,1]$freefraction[1],
    Data = list(
      # FreeFractionMethod = ancmat$Plasma[,,1]$freefraction[1],
      # FreeFractionTime = ,
      DecayCorrected = ancmat$Plasma[,,1]$Data[,,1]$decayCorrected[1],
      DecayCorrectionTime = ancmat$Plasma[,,1]$Data[,,1]$decayCorrectionTime[1],
      Type = ancmat$Plasma[,,1]$Data[,,1]$type[1],
      Labels = unlist(ancmat$Plasma[,,1]$Data[,,1]$labels),
      Units = unlist(ancmat$Plasma[,,1]$Data[,,1]$units),
      Values = unlist(ancmat$Plasma[,,1]$Data[,,1]$values)
    )
  )

  Metabolite = list(
    Data = list(
      Type = ancmat$Metabolite[,,1]$Data[,,1]$type[1],
      # Method = ancmat$Metabolite[,,1]$Data[1],
      Labels = unlist(ancmat$Metabolite[,,1]$Data[,,1]$labels),
      Units = unlist(ancmat$Metabolite[,,1]$Data[,,1]$units),
      Values = unlist(ancmat$Metabolite[,,1]$Data[,,1]$values)
    )
  )

  Blood_Discrete = list(
    Haematocrit = ancmat$Blood[,,1]$Discrete[,,1]$haematocrit[1],
    BloodDensity = ancmat$Blood[,,1]$Discrete[,,1]$bloodDensity[1],
    BloodDensityUnits = ancmat$Blood[,,1]$Discrete[,,1]$bloodDensityUnits[1],
    Data = list(
      Type = ancmat$Blood[,,1]$Discrete[,,1]$Data[,,1]$type[1],
      # Method = ancmat$Blood[,,1]$Discrete[,,1]$Data[1],
      Labels = unlist(ancmat$Blood[,,1]$Discrete[,,1]$Data[,,1]$labels),
      Units = unlist(ancmat$Blood[,,1]$Discrete[,,1]$Data[,,1]$units),
      Values = unlist(ancmat$Blood[,,1]$Discrete[,,1]$Data[,,1]$values),
      DecayCorrected = ancmat$Blood[,,1]$Discrete[,,1]$Data[,,1]$decayCorrected[1],
      DecayCorrectionTime = ancmat$Blood[,,1]$Discrete[,,1]$Data[,,1]$decayCorrectionTime[1]
    )
  )

  Blood_Continuous = list(
    WithdrawalRate = ancmat$Blood[,,1]$Continuous[,,1]$withdrawalRate[1],
    WithdrawalRateUnits = ancmat$Blood[,,1]$Continuous[,,1]$withdrawalRateUnits[1],
    TubingType = ancmat$Blood[,,1]$Continuous[,,1]$tubingType[1],
    TubingLength = ancmat$Blood[,,1]$Continuous[,,1]$tubingLength[1],
    DispersionConstant = ancmat$Blood[,,1]$Continuous[,,1]$Data[,,1]$dispersionFactor[1],
    DispersionConstantUnits = ancmat$Blood[,,1]$Continuous[,,1]$Data[,,1]$dispersionFactorUnits[1],
    DispersionCorrected = TRUE,
    Data = list(
      DecayCorrected = ancmat$Blood[,,1]$Continuous[,,1]$Data[,,1]$decayCorrected[1],
      DecayCorrectionTime = ancmat$Blood[,,1]$Continuous[,,1]$Data[,,1]$decayCorrectionTime[1],
      Type = ancmat$Blood[,,1]$Continuous[,,1]$Data[,,1]$type[1],
      Labels = unlist(ancmat$Blood[,,1]$Continuous[,,1]$Data[,,1]$labels),
      Units = unlist(ancmat$Blood[,,1]$Continuous[,,1]$Data[,,1]$units),
      Values = unlist(ancmat$Blood[,,1]$Continuous[,,1]$Data[,,1]$values)
    )
  )

  Blood <- list(
    Discrete = Blood_Discrete,
    Continuous = Blood_Continuous
  )

  bidsout <- list(
    Info = Info,
    Radiochem = Radiochem,
    Time = Time,
    Plasma = Plasma,
    Metabolite = Metabolite,
    Blood = Blood
  )

  # Fixing units

  if( bidsout$Plasma$Data$Units[3] == "nCi/ml" ) {
    bidsout$Plasma$Data$Units[3] = "kBq/ml"
    bidsout$Plasma$Data$Values[,3] =
      bidsout$Plasma$Data$Values[,3] * 0.037
  }

  if( bidsout$Blood$Discrete$Data$Units[3] == "nCi/ml" ) {
    bidsout$Blood$Discrete$Data$Units[3] = "kBq/ml"
    bidsout$Blood$Discrete$Data$Values[,3] =
      bidsout$Blood$Discrete$Data$Values[,3] * 0.037
  }

  if( bidsout$Blood$Continuous$Data$Units[2] == "nCi/ml" ) {
    bidsout$Blood$Continuous$Data$Units[2] = "kBq/ml"
    bidsout$Blood$Continuous$Data$Values[,2] =
      bidsout$Blood$Continuous$Data$Values[,3] * 0.037
  }

  return(bidsout)

}
